"""
Creates a CSV-to-LaTeX printer object.
"""

class texWriter:

    def __init__(self):
        pass

    def setupTexFilePackages(self, f):

        f.write(r'\documentclass{article}' + '\n')
        f.write(r'\usepackage[utf8]{inputenc}' + '\n')
        f.write(r'\usepackage{graphicx}' + '\n')
        f.write(r'\usepackage[table]{xcolor}' + '\n')
        f.write(r'\usepackage[a4paper,landscape,left=2cm, right=2cm, top=2cm, bottom=2.5cm, includehead, includefoot]{geometry}' + '\n')
        f.write(r'\usepackage{fancyhdr}' + '\n')
        f.write(r'\usepackage[german]{babel}' + '\n')
        f.write(r'\usepackage{caption}' + '\n\n')

        f.write(r'\newcommand\YUGE{\fontsize{100}{120}\selectfont}' + '\n\n')

        f.write(r'\newcommand{\fakesection}[1]{%' + '\n')
        f.write(r'\par\refstepcounter{section}% Increase section counter' + '\n')
        f.write(r'\sectionmark{#1}% Add section mark (header)' + '\n')
        f.write(r'\addcontentsline{toc}{section}{\protect\numberline{\thesection}#1}% Add section to ToC' + '\n')
        f.write(r'% Add more content here, if needed.' + '\n')
        f.write(r'}' + '\n\n')

        f.write(r'\newcommand{\fakesubsection}[1]{%' + '\n')
        f.write(r'\par\refstepcounter{subsection}% Increase subsection counter' + '\n')
        f.write(r'\subsectionmark{#1}% Add subsection mark (header)' + '\n')
        f.write(r'\addcontentsline{toc}{subsection}{\protect\numberline{\thesubsection}#1}% Add subsection to ToC' + '\n')
        f.write(r'% Add more content here, if needed.' + '\n')
        f.write(r'}' + '\n\n')

        f.write(r'\fancypagestyle{plain}{' + '\n')
        f.write(r'\fancyhf{}' + '\n')
        f.write(r'\lhead{\includegraphics[width=3cm]{img/hwz-logo.jpg}}' + '\n')
        f.write(r'\rhead{\includegraphics[width=3cm]{img/swissrei-logo.jpg}}' + '\n')
        f.write(r'\rfoot{Seite \thepage}' + '\n')
        f.write(r'\cfoot{Prof. Dr. Peter Ilg, Leiter Swiss Real Estate Institute}' + '\n')
        f.write(r'\lfoot{09.11.2018}' + '\n')
        f.write(r'}' + '\n\n')

        f.write(r'\pagestyle{plain}' + '\n')

    def writeTitlePage(self, f, mo_str='abcd', mo_plz='1234', mo_rooms='4.0', mo_city='abcity'):
        f.write(r'\begin{document}' + '\n')
        f.write(r'\vspace*{5cm}\noindent{\YUGE \underline{Gutachten zur Orts- oder Quartierüblichkeit}} \\' + '\n\n')
            
        f.write(r'\vspace{1cm} \noindent ' + mo_str + r'\\' + '\n')
        f.write(mo_rooms + ' Zimmer' + r'\\' + '\n')
        f.write(mo_plz + ' ' + mo_city + r'\\' + '\n')

    def writeHOTablePage(self, f, mo_dict):
        f.write(r'\clearpage' + '\n')
        f.write(r'\section{Details zum Hauptobjekt}' + '\n')
        f.write(r'Analyse der relevanten Vergleichskriterien.' + '\n')
        f.write(r'\begin{flushleft}' + '\n')
        f.write(r'\renewcommand{\arraystretch}{1.1}' + '\n')
        f.write(r'\setlength{\tabcolsep}{10pt}' + '\n')
        f.write(r'\begin{tabular}{ |l|l| } ' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Adresse & \cellcolor{lightgray}' + mo_dict['street'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Monatspreis &\\ ' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Nettomietzins & \cellcolor{lightgray}' + mo_dict['net_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Nebenkosten & \cellcolor{lightgray}' + mo_dict['ext_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Bruttomietzins & \cellcolor{lightgray}' + mo_dict['br_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Mietzins/m2 p.a. & \cellcolor{lightgray}' + mo_dict['m2_pa'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Lage \& Distanzen &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Historisch/Administrativ & \cellcolor{lightgray}' + mo_dict['plz_city'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Schule & \cellcolor{lightgray}' + mo_dict['d_school'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Einkaufsmöglichkeiten & \cellcolor{lightgray}' + mo_dict['d_shop'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Naherholung & \cellcolor{lightgray}' + mo_dict['d_fun'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'ÖV & \cellcolor{lightgray}' + mo_dict['d_public'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Grösse &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Zimmerzahl p.a. & \cellcolor{lightgray}' + mo_dict['rooms'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Fläche ($m^2$) & \cellcolor{lightgray}' + mo_dict['size'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Ausstattung &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Anzahl Nasszellen & \cellcolor{lightgray}' + mo_dict['bath'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Küche & \cellcolor{lightgray}' + mo_dict['kitchen'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Balkon & \cellcolor{lightgray}' + mo_dict['balkon'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Lift & \cellcolor{lightgray}' + mo_dict['lift'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Stockwerk & \cellcolor{lightgray}' + mo_dict['floor'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Baujahr &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Baujahr & \cellcolor{lightgray}' + mo_dict['year'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\end{tabular}' + '\n')
        f.write(r'\end{flushleft}' + '\n')

    def writeHOMacroPage(self, f, path):
        f.write(r'\clearpage' + '\n')
        f.write(r'\section{Analyse der Makrolage}' + '\n')
        f.write(r'\begin{figure}[!htbp]' + '\n')
        f.write(r'\begin{minipage}[c]{0.67\textwidth}' + '\n')
        f.write(r'\includegraphics[width=\textwidth]{'+ path +'}' + '\n')
        f.write(r'\end{minipage}\hfill' + '\n')
        f.write(r'\begin{minipage}[c]{0.3\textwidth}' + '\n')
        f.write(r'\begin{itemize}' + '\n')
        f.write(r'\item ÖV und Bahnhof in Gehdistanz' + '\n')
        f.write(r'\item Schulen sind schnell erreichbar' + '\n')
        f.write(r'\item Einkaufszentren nur wenige Minuten entfernt und ist nicht weit von Nachtclubs' + '\n')
        f.write(r'\item Nahe gelegen an populären Einkaufszentren' + '\n')
        f.write(r'\end{itemize}' + '\n')
        f.write(r'\end{minipage}' + '\n')
        f.write(r'\end{figure}' + '\n')

    def writeHOMikroPage(self, f, path):
        f.write(r'\clearpage' + '\n')
        f.write(r'\section{Analyse der Makrolage}' + '\n')
        f.write(r'\begin{figure}[!htbp]' + '\n')
        f.write(r'\begin{minipage}[c]{0.67\textwidth}' + '\n')
        f.write(r'\includegraphics[width=\textwidth]{'+ path +'}' + '\n')
        f.write(r'\end{minipage}\hfill' + '\n')
        f.write(r'\begin{minipage}[c]{0.3\textwidth}' + '\n')
        f.write(r'\begin{itemize}' + '\n')
        f.write(r'\item ÖV und Bahnhof in Gehdistanz' + '\n')
        f.write(r'\item Schulen sind schnell erreichbar' + '\n')
        f.write(r'\item Einkaufszentren nur wenige Minuten entfernt und ist nicht weit von Nachtclubs' + '\n')
        f.write(r'\item Nahe gelegen an populären Einkaufszentren' + '\n')
        f.write(r'\end{itemize}' + '\n')
        f.write(r'\end{minipage}' + '\n')
        f.write(r'\end{figure}' + '\n')

    def writeCompareGraph(self, f, mo_dict, vo_dict):
        pass
    def writeCompareTable(self, f, mo_dict, vo_dict):
        pass # if more than 5 VO exist
    def writeVOMacroPage(self, f, mo_dict, vo_dict, mo_makro='img/vo-makro.png'):
        f.write(r'\clearpage' + '\n')
        f.write(r'\section{' + vo_dict['street'] + '}' + '\n')
        f.write(r'\subsection{Übersicht der Vergleichskriterien und Analyse der Makrolage}' + '\n')
        f.write(r'\begin{figure}[!htbp]' + '\n')
        f.write(r'\begin{minipage}[c]{0.55\textwidth}' + '\n')
        f.write(r'\includegraphics[width=\textwidth]{' + mo_makro + '}' + '\n')
        f.write(r'\end{minipage}\hfill' + '\n')
        f.write(r'\begin{minipage}[c]{0.44\textwidth}' + '\n')
        f.write(r'\begin{flushleft}' + '\n')
        f.write(r'\renewcommand{\arraystretch}{1.1}' + '\n')
        f.write(r'\setlength{\tabcolsep}{10pt}' + '\n')
        f.write(r'\begin{tabular}{ |l|l|l| } ' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Adresse & \cellcolor{lightgray}' + mo_dict['street'] + '&' + vo_dict['street'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Monatspreis & &\\ ' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Nettomietzins & \cellcolor{lightgray}' + mo_dict['net_mo'] + '&' + vo_dict['net_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Nebenkosten & \cellcolor{lightgray}' + mo_dict['ext_mo'] + '&' + vo_dict['ext_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Bruttomietzins & \cellcolor{lightgray}' + mo_dict['br_mo'] + '&' + vo_dict['br_mo'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Mietzins/m2 p.a. & \cellcolor{lightgray}' + mo_dict['m2_pa'] + '&' + vo_dict['m2_pa'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Lage \& Distanzen & &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Historisch/Administrativ & \cellcolor{lightgray}' + mo_dict['plz_city'] + '&' + vo_dict['plz_city'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Schule & \cellcolor{lightgray}' + mo_dict['d_school'] + '&' + vo_dict['d_school'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Einkaufsmöglichkeiten & \cellcolor{lightgray}' + mo_dict['d_shop'] + '&' + vo_dict['d_shop'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Naherholung & \cellcolor{lightgray}' + mo_dict['d_fun'] + '&' + vo_dict['d_fun'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'ÖV & \cellcolor{lightgray}' + mo_dict['d_public'] + '&' + vo_dict['d_public'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Grösse & &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Zimmerzahl p.a. & \cellcolor{lightgray}' + mo_dict['rooms'] + '&' + vo_dict['rooms'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Fläche ($m^2$) & \cellcolor{lightgray}' + mo_dict['size'] + '&' + vo_dict['size'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Ausstattung & & \\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Anzahl Nasszellen & \cellcolor{lightgray}' + mo_dict['bath'] + '&' + vo_dict['bath'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Küche & \cellcolor{lightgray}' + mo_dict['kitchen'] + '&' + vo_dict['kitchen'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Balkon & \cellcolor{lightgray}' + mo_dict['balkon'] + '&' + vo_dict['balkon'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Lift & \cellcolor{lightgray}' + mo_dict['lift'] + '&' + vo_dict['lift'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Stockwerk & \cellcolor{lightgray}' + mo_dict['floor'] + '&' + vo_dict['floor'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\rowcolor{gray} Baujahr & &\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'Baujahr & \cellcolor{lightgray}' + mo_dict['year'] + '&' + vo_dict['year'] + r'\\' + '\n')
        f.write(r'\hline' + '\n')
        f.write(r'\end{tabular}' + '\n')
        f.write(r'\end{flushleft}' + '\n')
        f.write(r'\end{minipage}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write(r'\end{document}')